### ISSUE TITLE
discord.js-commando

### ISSUE THREAD

**Issue by rinzler100** [Nukestye/Zodiac#10]
Im having a problem when trying to run main.js, it gives me errors about discord.js-commando

**Comment by Nukestye** [comment]
@rinzler100  Sorry for the delayed response but have you tried installing the discord.js-commando module? Also can you please let me see the output it gives.

**Comment by rinzler100** [comment]
This could have been the case, thank you, I just realized what commando is. I’m a bit new here (: 
I’ll leave a new issue if it continues, thanks

**Comment by Nukestye** [comment]
Just continue here if the issue persists.

**Comment by rinzler100** [comment]
Ok 👍🏼

**Comment by Nukestye** [comment]
The issue is closed due to inactivity. Reopen if it continues.
